// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcIOnXohV0bF53bCLkMM9udSWm1JfhZi0',
    appId: '1:423470253720:web:fea339253ee90e3140f2ed',
    messagingSenderId: '423470253720',
    projectId: 'crud-firestore-f2ba1',
    authDomain: 'crud-firestore-f2ba1.firebaseapp.com',
    storageBucket: 'crud-firestore-f2ba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPEdBg5sF0RNB7AFzQ-pGjzCxhxNVBpUY',
    appId: '1:423470253720:android:d44f8add789879b940f2ed',
    messagingSenderId: '423470253720',
    projectId: 'crud-firestore-f2ba1',
    storageBucket: 'crud-firestore-f2ba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeQsjrtJs-PLOPipNgX3qrvIKObTzYU8',
    appId: '1:423470253720:ios:9ebcb8f993d54f6040f2ed',
    messagingSenderId: '423470253720',
    projectId: 'crud-firestore-f2ba1',
    storageBucket: 'crud-firestore-f2ba1.appspot.com',
    iosClientId: '423470253720-vjn15n6bboopn5clbftuvratsl96sfsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOeQsjrtJs-PLOPipNgX3qrvIKObTzYU8',
    appId: '1:423470253720:ios:9ebcb8f993d54f6040f2ed',
    messagingSenderId: '423470253720',
    projectId: 'crud-firestore-f2ba1',
    storageBucket: 'crud-firestore-f2ba1.appspot.com',
    iosClientId: '423470253720-vjn15n6bboopn5clbftuvratsl96sfsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.youtubeApi',
  );
}
